#!/usr/bin/env bash
set -euo pipefail

APP_NAME="xui-manager-panel-frontend"
APP_DIR="${APP_DIR:-/var/www/xui-manager-panel-frontend}"
REPO_URL="${REPO_URL:-https://github.com/HaydenSmith1121/xui-manager-panel-frontend.git}"
BRANCH="${BRANCH:-main}"
API_BASE_URL="${API_BASE_URL:-}"
NGINX_CONF="${NGINX_CONF:-/etc/nginx/sites-available/${APP_NAME}.conf}"
NGINX_LINK="${NGINX_LINK:-/etc/nginx/sites-enabled/${APP_NAME}.conf}"
FRONTEND_DEFAULT_SERVER="${FRONTEND_DEFAULT_SERVER:-1}"

detect_nginx_listen_port() {
  [ -f "$1" ] || return 1
  awk '
    $1 == "listen" {
      value = $2
      gsub(/;/, "", value)
      sub(/.*:/, "", value)
      if (value ~ /^[0-9]+$/) {
        print value
        exit
      }
    }
  ' "$1"
}

detect_nginx_server_name() {
  [ -f "$1" ] || return 1
  awk '
    $1 == "server_name" {
      for (i = 2; i <= NF; i++) {
        gsub(/;/, "", $i)
        if ($i != "") {
          print $i
          exit
        }
      }
    }
  ' "$1"
}

detect_nginx_backend_upstream() {
  [ -f "$1" ] || return 1
  awk '
    $1 == "proxy_pass" {
      value = $2
      gsub(/;/, "", value)
      print value
      exit
    }
  ' "$1"
}

nginx_config_has_backend_proxy() {
  [ -f "$1" ] && grep -Eq '^[[:space:]]*proxy_pass[[:space:]]+' "$1"
}

if [ -z "${FRONTEND_SERVER_NAME+x}" ]; then
  EXISTING_FRONTEND_SERVER_NAME="$(detect_nginx_server_name "$NGINX_CONF" || true)"
  FRONTEND_SERVER_NAME="${EXISTING_FRONTEND_SERVER_NAME:-_}"
else
  FRONTEND_SERVER_NAME="${FRONTEND_SERVER_NAME:-_}"
fi

if [ -z "${FRONTEND_LISTEN_PORT+x}" ]; then
  EXISTING_FRONTEND_LISTEN_PORT="$(detect_nginx_listen_port "$NGINX_CONF" || true)"
  FRONTEND_LISTEN_PORT="${EXISTING_FRONTEND_LISTEN_PORT:-80}"
else
  FRONTEND_LISTEN_PORT="${FRONTEND_LISTEN_PORT:-80}"
fi

if [ -z "${BACKEND_UPSTREAM+x}" ]; then
  EXISTING_BACKEND_UPSTREAM="$(detect_nginx_backend_upstream "$NGINX_CONF" || true)"
  BACKEND_UPSTREAM="${EXISTING_BACKEND_UPSTREAM:-http://127.0.0.1:25889}"
else
  BACKEND_UPSTREAM="${BACKEND_UPSTREAM:-http://127.0.0.1:25889}"
fi

if [ -z "${ENABLE_BACKEND_PROXY+x}" ]; then
  if [ -f "$NGINX_CONF" ]; then
    if nginx_config_has_backend_proxy "$NGINX_CONF"; then
      ENABLE_BACKEND_PROXY=1
    else
      ENABLE_BACKEND_PROXY=0
    fi
  else
    ENABLE_BACKEND_PROXY=1
  fi
else
  ENABLE_BACKEND_PROXY="${ENABLE_BACKEND_PROXY:-1}"
fi

DEFAULT_SERVER_SUFFIX=""
if [ "$FRONTEND_DEFAULT_SERVER" = "1" ]; then
  DEFAULT_SERVER_SUFFIX=" default_server"
fi

if [ "$(id -u)" -ne 0 ]; then
  echo "Please run this installer as root."
  exit 1
fi

export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y ca-certificates curl git nginx

if [ -d "${APP_DIR}/.git" ]; then
  git -C "$APP_DIR" fetch origin "$BRANCH"
  git -C "$APP_DIR" checkout "$BRANCH"
  git -C "$APP_DIR" pull --ff-only origin "$BRANCH"
else
  rm -rf "$APP_DIR"
  git clone --branch "$BRANCH" "$REPO_URL" "$APP_DIR"
fi

cat > "${APP_DIR}/config.js" <<EOF
// Generated by deploy/install.sh. Re-run install.sh or upgrade.sh to change it.
window.XUI_MANAGER_API_BASE_URL = "${API_BASE_URL}";
EOF

mkdir -p "$(dirname "$NGINX_CONF")" "$(dirname "$NGINX_LINK")"

if [ "$ENABLE_BACKEND_PROXY" = "1" ]; then
  cat > "$NGINX_CONF" <<EOF
server {
    listen ${FRONTEND_LISTEN_PORT}${DEFAULT_SERVER_SUFFIX};
    server_name ${FRONTEND_SERVER_NAME};

    root ${APP_DIR};
    index index.html;

    location / {
        try_files \$uri \$uri/ /index.html;
    }

    location ^~ /api/ {
        proxy_pass ${BACKEND_UPSTREAM};
        proxy_http_version 1.1;
        proxy_set_header Host \$http_host;
        proxy_set_header X-Forwarded-Host \$http_host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location ^~ /sub/ {
        proxy_pass ${BACKEND_UPSTREAM};
        proxy_http_version 1.1;
        proxy_set_header Host \$http_host;
        proxy_set_header X-Forwarded-Host \$http_host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
EOF
else
  cat > "$NGINX_CONF" <<EOF
server {
    listen ${FRONTEND_LISTEN_PORT}${DEFAULT_SERVER_SUFFIX};
    server_name ${FRONTEND_SERVER_NAME};

    root ${APP_DIR};
    index index.html;

    location / {
        try_files \$uri \$uri/ /index.html;
    }
}
EOF
fi

ln -sf "$NGINX_CONF" "$NGINX_LINK"
if [ "$FRONTEND_DEFAULT_SERVER" = "1" ]; then
  # Fully hand the HTTP default site to this panel. Some Ubuntu images keep the
  # welcome page as a regular enabled file instead of a symlink, so remove either
  # form before nginx is reloaded.
  rm -f /etc/nginx/sites-enabled/default
fi
nginx -t
systemctl enable --now nginx
systemctl reload nginx

if command -v ufw >/dev/null 2>&1 && ufw status | grep -qw active; then
  ufw allow "${FRONTEND_LISTEN_PORT}/tcp" || true
fi

echo
echo "Installed ${APP_NAME}."
echo "Frontend: http://SERVER_IP:${FRONTEND_LISTEN_PORT}/"
echo "Nginx server_name: ${FRONTEND_SERVER_NAME}"
if [ -n "$API_BASE_URL" ]; then
  echo "API base: ${API_BASE_URL}"
else
  echo "API base: same-origin"
fi
if [ "$ENABLE_BACKEND_PROXY" = "1" ]; then
  echo "Backend proxy: /api and /sub -> ${BACKEND_UPSTREAM}"
fi
echo "Nginx config: ${NGINX_CONF}"
