#!/usr/bin/env bash
set -euo pipefail

APP_NAME="${APP_NAME:-xui-manager-panel-frontend}"
DEPLOY_ROOT="${DEPLOY_ROOT:-/var/www/xui-manager-panel-frontend}"
SOURCE_DIR="${SOURCE_DIR:-$(pwd)}"
RELEASES_DIR="${RELEASES_DIR:-${DEPLOY_ROOT}/releases}"
CURRENT_LINK="${CURRENT_LINK:-${DEPLOY_ROOT}/current}"
PREVIOUS_LINK="${PREVIOUS_LINK:-${DEPLOY_ROOT}/previous}"
KEEP_RELEASES="${KEEP_RELEASES:-5}"
API_BASE_URL="${API_BASE_URL:-}"
NGINX_CONF="${NGINX_CONF:-/etc/nginx/sites-available/${APP_NAME}.conf}"
NGINX_LINK="${NGINX_LINK:-/etc/nginx/sites-enabled/${APP_NAME}.conf}"
FRONTEND_DEFAULT_SERVER="${FRONTEND_DEFAULT_SERVER:-1}"
FRONTEND_SERVER_NAME="${FRONTEND_SERVER_NAME:-_}"
FRONTEND_LISTEN_PORT="${FRONTEND_LISTEN_PORT:-80}"
ENABLE_BACKEND_PROXY="${ENABLE_BACKEND_PROXY:-1}"
BACKEND_UPSTREAM="${BACKEND_UPSTREAM:-http://127.0.0.1:25889}"
HEALTHCHECK_URL="${HEALTHCHECK_URL:-http://127.0.0.1:${FRONTEND_LISTEN_PORT}/}"

if [ "$(id -u)" -ne 0 ]; then
  echo "Please run this Jenkins deploy as root or through sudo."
  exit 1
fi

if [ ! -f "${SOURCE_DIR}/index.html" ] || [ ! -f "${SOURCE_DIR}/app.js" ]; then
  echo "SOURCE_DIR must point to the frontend workspace. Current: ${SOURCE_DIR}"
  exit 1
fi

GIT_COMMIT_SHORT="${GIT_COMMIT:-manual}"
GIT_COMMIT_SHORT="${GIT_COMMIT_SHORT:0:12}"
RELEASE_ID="${RELEASE_ID:-$(date +%Y%m%d%H%M%S)-${GIT_COMMIT_SHORT}}"
RELEASE_DIR="${RELEASES_DIR}/${RELEASE_ID}"
OLD_TARGET=""
if [ -L "$CURRENT_LINK" ]; then
  OLD_TARGET="$(readlink -f "$CURRENT_LINK" || true)"
fi

rollback_to_previous() {
  if [ -n "$OLD_TARGET" ] && [ -d "$OLD_TARGET" ]; then
    echo "Deploy failed. Rolling back to ${OLD_TARGET}."
    ln -sfn "$OLD_TARGET" "$CURRENT_LINK"
    nginx -t && systemctl reload nginx || true
  fi
}

trap rollback_to_previous ERR

mkdir -p "$RELEASES_DIR"
if [ -e "$RELEASE_DIR" ]; then
  echo "Release already exists: ${RELEASE_DIR}"
  exit 1
fi
mkdir -p "$RELEASE_DIR"

if command -v rsync >/dev/null 2>&1; then
  rsync -a --delete --exclude ".git" --exclude "__pycache__" --exclude ".pytest_cache" "${SOURCE_DIR}/" "${RELEASE_DIR}/"
else
  tar -C "$SOURCE_DIR" --exclude="./.git" --exclude="./__pycache__" --exclude="./.pytest_cache" -cf - . | tar -C "$RELEASE_DIR" -xf -
fi

cat > "${RELEASE_DIR}/config.js" <<EOF
// Generated by deploy/jenkins-deploy.sh.
window.XUI_MANAGER_API_BASE_URL = "${API_BASE_URL}";
EOF

if command -v node >/dev/null 2>&1; then
  node --check "${RELEASE_DIR}/app.js"
fi

DEFAULT_SERVER_SUFFIX=""
if [ "$FRONTEND_DEFAULT_SERVER" = "1" ]; then
  DEFAULT_SERVER_SUFFIX=" default_server"
fi

mkdir -p "$(dirname "$NGINX_CONF")" "$(dirname "$NGINX_LINK")"
cat > "$NGINX_CONF" <<EOF
server {
    listen ${FRONTEND_LISTEN_PORT}${DEFAULT_SERVER_SUFFIX};
    server_name ${FRONTEND_SERVER_NAME};

    root ${CURRENT_LINK};
    index index.html;

    location / {
        try_files \$uri \$uri/ /index.html;
    }
EOF
if [ "$ENABLE_BACKEND_PROXY" = "1" ]; then
  cat >> "$NGINX_CONF" <<EOF

    location ^~ /api/ {
        proxy_pass ${BACKEND_UPSTREAM};
        proxy_http_version 1.1;
        proxy_set_header Host \$http_host;
        proxy_set_header X-Forwarded-Host \$http_host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location ^~ /sub/ {
        proxy_pass ${BACKEND_UPSTREAM};
        proxy_http_version 1.1;
        proxy_set_header Host \$http_host;
        proxy_set_header X-Forwarded-Host \$http_host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
EOF
fi
cat >> "$NGINX_CONF" <<EOF
}
EOF

ln -sf "$NGINX_CONF" "$NGINX_LINK"
if [ "$FRONTEND_DEFAULT_SERVER" = "1" ]; then
  rm -f /etc/nginx/sites-enabled/default
fi

if [ -n "$OLD_TARGET" ] && [ -d "$OLD_TARGET" ]; then
  ln -sfn "$OLD_TARGET" "$PREVIOUS_LINK"
fi
ln -sfn "$RELEASE_DIR" "$CURRENT_LINK"

nginx -t
systemctl enable --now nginx
systemctl reload nginx
curl -fsSI "$HEALTHCHECK_URL" >/dev/null

trap - ERR
find "$RELEASES_DIR" -mindepth 1 -maxdepth 1 -type d -printf "%T@ %p\n" | sort -rn | awk "NR>${KEEP_RELEASES} {print \$2}" | while IFS= read -r old_release; do
  [ "$(readlink -f "$CURRENT_LINK" || true)" = "$old_release" ] && continue
  [ "$(readlink -f "$PREVIOUS_LINK" || true)" = "$old_release" ] && continue
  rm -rf "$old_release"
done

echo "Deployed ${APP_NAME} release ${RELEASE_ID}."
echo "Current: ${CURRENT_LINK} -> $(readlink -f "$CURRENT_LINK")"
