#!/usr/bin/env bash
set -euo pipefail

APP_NAME="xui-manager-panel-frontend"
APP_DIR="${APP_DIR:-/var/www/xui-manager-panel-frontend}"
BRANCH="${BRANCH:-main}"
API_BASE_URL="${API_BASE_URL:-}"
ENABLE_BACKEND_PROXY="${ENABLE_BACKEND_PROXY:-1}"
BACKEND_UPSTREAM="${BACKEND_UPSTREAM:-http://127.0.0.1:25888}"
FRONTEND_SERVER_NAME="${FRONTEND_SERVER_NAME:-_}"
FRONTEND_LISTEN_PORT="${FRONTEND_LISTEN_PORT:-80}"
NGINX_CONF="${NGINX_CONF:-/etc/nginx/sites-available/${APP_NAME}.conf}"
NGINX_LINK="${NGINX_LINK:-/etc/nginx/sites-enabled/${APP_NAME}.conf}"

if [ "$(id -u)" -ne 0 ]; then
  echo "Please run this upgrade as root."
  exit 1
fi

if [ ! -d "${APP_DIR}/.git" ]; then
  echo "${APP_DIR} is not a git checkout. Run deploy/install.sh first."
  exit 1
fi

git -C "$APP_DIR" fetch origin "$BRANCH"
git -C "$APP_DIR" checkout "$BRANCH"
git -C "$APP_DIR" pull --ff-only origin "$BRANCH"

cat > "${APP_DIR}/config.js" <<EOF
// Generated by deploy/upgrade.sh. Re-run upgrade.sh to change it.
window.XUI_MANAGER_API_BASE_URL = "${API_BASE_URL}";
EOF

mkdir -p "$(dirname "$NGINX_CONF")" "$(dirname "$NGINX_LINK")"

if [ "$ENABLE_BACKEND_PROXY" = "1" ]; then
  cat > "$NGINX_CONF" <<EOF
server {
    listen ${FRONTEND_LISTEN_PORT};
    server_name ${FRONTEND_SERVER_NAME};

    root ${APP_DIR};
    index index.html;

    location / {
        try_files \$uri \$uri/ /index.html;
    }

    location ^~ /api/ {
        proxy_pass ${BACKEND_UPSTREAM};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location ^~ /sub/ {
        proxy_pass ${BACKEND_UPSTREAM};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
EOF
else
  cat > "$NGINX_CONF" <<EOF
server {
    listen ${FRONTEND_LISTEN_PORT};
    server_name ${FRONTEND_SERVER_NAME};

    root ${APP_DIR};
    index index.html;

    location / {
        try_files \$uri \$uri/ /index.html;
    }
}
EOF
fi

ln -sf "$NGINX_CONF" "$NGINX_LINK"
nginx -t
systemctl reload nginx

echo "Upgraded ${APP_NAME}."
